### ISSUE TITLE
quilt doesn't work serverside

### ISSUE THREAD

**Issue by annahla** [DakotaPride/Hibernal-Herbs#10]
FabricModelPredicateProviderRegistry in common.utils is a serverside class & those registries should be in client. I was able to get it booting by just moving those lines to the client init code

**Comment by DakotaPride** [comment]
Thank you for bringing this to my attention, should be fixed soon! (I will most likely release a patch later this week) Apologies for the inconvenience!

**Comment by DakotaPride** [comment]
Sorry for the LONG wait, but 0.9 is now released on Modrinth with (hopefully) a fix to this issue. Let me know if it either persists or if there are any other issues that you may experience in the most recent version. Do keep in mind as well that 0.9 is currently only available for MC version 1.20x, so it will not be functional in versions prior to that. Again, let me know if there are any other issues that you experience in regard to this update or earlier.
