### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by ryleu** [DakotaPride/Hibernal-Herbs#13]
I'd love to see a wiki for the mod... maybe here on GitHub?

**Comment by DakotaPride** [comment]
There is Patchouli integration available if you're looking for more information on certain features. However, I understand that there may be some information missing from this. If you have a suggestion about what to add to the Patchouli book, feel free to let me know! (sorry for the long wait on getting a response, was busy with one of my other mods' next update)

**Comment by ryleu** [comment]
patchouli does not seem to be working and many people like to have the docs in a browser window. iirc there's a way to render & host patchouli on github pages, but i'm not super familiar with it

**Comment by DakotaPride** [comment]
The Patchouli issue should now be fixed (available on Modrinth, currently waiting for approval on Curseforge).

I'm not sure how to host Patchouli inside GitHub pages, so if you find any resources relating to the subject, I'll be more than happy to try.
