### ISSUE TITLE
Food items have extremely high saturation

### ISSUE THREAD

**Issue by lilypuree** [DakotaPride/Hibernal-Herbs#14]
I suspect that the intended saturation value is being passed into saturationMod()
the saturation modifier value gets multiplied by nutrition and 2 to get the actual saturation value. For example, a herb blend with nutrition 7, saturation mod 6 will get 84 saturation, instantly maxing out the saturation bar. In vanilla, even enchanted golden apples only have 1.2 saturation modifiers!

**Comment by DakotaPride** [comment]
I assume that this issue is happening in Forge? This should be fixed shortly, thank you for reporting this issue and I will let you know when a fix becomes available on both Modrinth and Curseforge!

**Comment by DakotaPride** [comment]
Now available on [Modrinth](https://modrinth.com/mod/hibernal-herbs/versions)!

**Comment by DakotaPride** [comment]
Now, [Curseforge](https://legacy.curseforge.com/minecraft/mc-mods/hibernal-herbs/files/all) is approved!
