### ISSUE TITLE
Infinite Loop Crashing Server

### ISSUE THREAD

**Issue by Jack-Ashman** [DakotaPride/Hibernal-Herbs#15]
Looks like the MyquesteSaplingGenerator.java file has an infinite loop inside it that's causing a crash on the server that we're playing on.

![image](https://github.com/DakotaPride/Hibernal-Herbs/assets/91268292/c0633dec-1224-4e23-83fb-168ce492774d)

![image](https://github.com/DakotaPride/Hibernal-Herbs/assets/91268292/a2291418-e56d-4209-b141-37095724c1ad)

That error just goes on until the log ends.

**Comment by DakotaPride** [comment]
Should be fixed now on Modrinth, currently waiting on Curseforge approval!

**Comment by DakotaPride** [comment]
should now be approved on Curseforge!
