### ISSUE TITLE
Version 1.1-hotfix-5 and above don't work on servers

### ISSUE THREAD

**Issue by Naixatloz** [DakotaPride/Hibernal-Herbs#16]
The server fails to start, with the following details.

> 	Mod File: /home/container/mods/HibernalHerbs-forge-1.20.1-1.2-hotfix-1.jar
	Failure message: Hibernal Herbs (hibernalherbs) has failed to load correctly
		java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/entity/EntityRenderer for invalid dist DEDICATED_SERVER
	Mod Version: 1.2-hotfix-1
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/entity/EntityRenderer for invalid dist DEDICATED_SERVER

[crash-2024-06-02_07.28.38-fml.txt](https://github.com/user-attachments/files/15524483/crash-2024-06-02_07.28.38-fml.txt)

**Comment by DakotaPride** [comment]
Have you done this?
<img width="719" alt="image" src="https://github.com/DakotaPride/Hibernal-Herbs/assets/82760983/462fed8c-8ccb-4707-9fdb-5573bfcb4536">
Also, unless you're using other mods that require Sinytra Connector, there is no reason to use the mod as Hibernal Herbs offers support for both Forge and Fabric modloaders (and should work fine on Neoforge and Quilt)

**Comment by DakotaPride** [comment]
Sidenote, the wrong version was specified in your title

**Comment by Naixatloz** [comment]
I'm using Sinytra for a lot of other stuff. Also this _is_ a problem I've been having since hotfix 5, and I've just been checking every subsequent version to see if it's fixed.

**Comment by DakotaPride** [comment]
2 things, first: Report any and every issue (unless you notice that it's been reported already). I had no idea that this was happening up until this report. Second, please install the latest Fabric/Quilt version of Hibernal Herbs, it looks like you're using the Forge version of the mod according to the crash report.

**Comment by Naixatloz** [comment]
Fabric version works.
