### ISSUE TITLE
[Fabric 1.19.2] Parsing errors loading custom advancements

### ISSUE THREAD

**Issue by kingkuys2123** [DakotaPride/Hibernal-Herbs#2]
**Fabric 0.14.12**
**Fabric API 0.72.0**
**HibernalHerbs 0.5.1**
**Java 8 Update 351**

>> [09:14:20] [Render thread/ERROR]: Parsing error loading custom advancement hibernalherbs:recipes/food/blend_glowing_smoked: Unknown item id 'hibernalherbs:blend_glowing'

>> [09:14:20] [Render thread/ERROR]: Parsing error loading custom advancement hibernalherbs:recipes/food/herb_from_pounded_herb: Expected recipe to be a string, was an array (["hi...a"])

>> [09:14:20] [Render thread/ERROR]: Parsing error loading custom advancement hibernalherbs:recipes/food/pounded_herb: Expected recipe to be a string, was an array (["hi...a"])

**Comment by DakotaPride** [comment]
Should be fixed v0.5.2, which should hopefully be able to release within the next few days, maybe even later today. If you have any other issues that you would like to report, feel free to create another report as such!
