### ISSUE TITLE
[1.19.2 Forge /Fabric] Herbs with colored tips that looks like flowers are not tagged as minecraft:small_flowers

### ISSUE THREAD

**Issue by TelepathicGrunt** [DakotaPride/Hibernal-Herbs#5]
Just copying from discord to here to keep track. Using HibernalHerbs-forge-1.19.2-0.6.jar, it seems these herbs that seem like they got flowering tips are not tagged as small flowers. 
![image](https://user-images.githubusercontent.com/40846040/219684490-9d0de98a-711a-4c38-b0f6-e40dd9cc7c7f.png)
![image](https://user-images.githubusercontent.com/40846040/219684771-f4f69d4d-60d3-4055-9e7e-9a321db8f3bb.png)

**Comment by DakotaPride** [comment]
Should now be fixed, just making sure that there aren't any other bugs related to this before releasing the quick patch

**Comment by DakotaPride** [comment]
@TelepathicGrunt Just uploaded the release(s) for both Forge & Fabric, let me know if the issue you're experiencing persists!
