### ISSUE TITLE
Empty Tag in Crafting recipe

### ISSUE THREAD

**Issue by katubug** [DakotaPride/Hibernal-Herbs#8]
Hi! A user just reported this to me - apparently some of the recipes use empty tags?

https://cdn.discordapp.com/attachments/1078785618953375805/1090798118368444506/20230329_173400.jpg

https://cdn.discordapp.com/attachments/1078785618953375805/1090798118804656158/20230329_173407.jpg

**Comment by katubug** [comment]
Thanks! Looking forward to the update! :)

**Comment by DakotaPride** [comment]
I apologize for the longish wait, but I have finally updated the mod! Feel free to let me know if the issue still persists after updating!

**Comment by katubug** [comment]
Thanks for the update! No worries about the wait. :) Life happens! And I'll
keep you posted!
