### ISSUE TITLE
[1.19.2 Forge] Sage texture is not set to cutout

### ISSUE THREAD

**Issue by TelepathicGrunt** [DakotaPride/Hibernal-Herbs#9]
Currently using: HibernalHerbs-forge-1.19.2-0.8.jar

Not much else to say lol. Should be a quick fix by specifying the render type for the plant
![image](https://user-images.githubusercontent.com/40846040/231808052-b5967e63-9bb0-4aaa-b367-f0ea5a1da45a.png)

**Comment by DakotaPride** [comment]
Thank you for bringing this to my attention, I'll release a fix for this soon (while a minor fix, currently having some troubles with Intellij) I'll let you know when 0.8.1 is up on Curseforge/is done!

**Comment by DakotaPride** [comment]
0.8.1 is currently waiting to be approved on Curseforge right now! Thank you for your patience with the issue, let me know if the issue persists or if anything else comes up!
